(()=> {
  const mount = document.getElementById('three-tracking');
  if (!mount || mount.dataset.booted) return;
  mount.dataset.booted = '1';
  const threeUrl='https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
  const gltfUrl='https://cdn.jsdelivr.net/npm/three@0.179.1/examples/jsm/loaders/GLTFLoader.js';
  const start=async()=>{try{const T=await import(threeUrl);const {GLTFLoader}=await import(gltfUrl);build(T,GLTFLoader)}catch(e){console.error('NavRakhshak 3D boot failed:',e);mount.classList.add('fallback')}};
  function build(T,GLTFLoader){
    const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const scene=new T.Scene();scene.background=new T.Color(0x020a12);scene.fog=new T.FogExp2(0x061421,.0095);
    const camera=new T.PerspectiveCamera(43,1,.1,1200),renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.8));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;mount.appendChild(renderer.domElement);
    scene.add(new T.HemisphereLight(0x9fdcff,0x020914,1.7));const key=new T.DirectionalLight(0xffc49e,3.1);key.position.set(-30,42,18);scene.add(key);
    const fill=new T.PointLight(0x3aaeff,18,100,2);fill.position.set(22,10,-18);scene.add(fill);const orange=new T.PointLight(0xf25a22,12,55,2);orange.position.set(-8,5,8);scene.add(orange);
    const oceanGeo=new T.PlaneGeometry(260,260,110,110),ocean=new T.Mesh(oceanGeo,new T.MeshStandardMaterial({color:0x062a45,roughness:.24,metalness:.38,transparent:true,opacity:.96}));ocean.rotation.x=-Math.PI/2;ocean.position.y=-1.15;scene.add(ocean);
    const oceanPos=oceanGeo.attributes.position,oceanBase=new Float32Array(oceanPos.array),grid=new T.GridHelper(210,42,0x2b91bd,0x16435c);grid.position.y=-1.02;grid.material.transparent=true;grid.material.opacity=.18;scene.add(grid);
    const horizon=new T.Mesh(new T.RingGeometry(85,118,96),new T.MeshBasicMaterial({color:0x0c5d80,transparent:true,opacity:.13,side:T.DoubleSide}));horizon.rotation.x=-Math.PI/2;horizon.position.y=-.95;scene.add(horizon);
    const pc=innerWidth<700?850:1700,pg=new T.BufferGeometry(),pa=new Float32Array(pc*3);for(let i=0;i<pc;i++){pa[i*3]=(Math.random()-.5)*210;pa[i*3+1]=Math.random()*42+1;pa[i*3+2]=(Math.random()-.5)*210}pg.setAttribute('position',new T.BufferAttribute(pa,3));scene.add(new T.Points(pg,new T.PointsMaterial({color:0x9edfff,size:.11,transparent:true,opacity:.48,depthWrite:false})));
    const rings=new T.Group();rings.position.y=-.92;scene.add(rings);[7,13,20,28].forEach((radius,i)=>{const q=new T.Mesh(new T.RingGeometry(radius-.045,radius+.045,128),new T.MeshBasicMaterial({color:i===3?0x66d9ff:0xf25a22,transparent:true,opacity:i===3?.26:.16,side:T.DoubleSide}));q.rotation.x=-Math.PI/2;rings.add(q)});
    const sweep=new T.Mesh(new T.CircleGeometry(28,64,-.12,Math.PI/5),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.085,side:T.DoubleSide,blending:T.AdditiveBlending}));sweep.rotation.x=-Math.PI/2;sweep.position.y=.08;rings.add(sweep);
    const geofence=new T.Group();geofence.position.y=.4;scene.add(geofence);const fence=new T.Mesh(new T.CylinderGeometry(15,15,5.5,96,1,true),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.035,wireframe:true}));geofence.add(fence);const fenceTop=new T.Mesh(new T.TorusGeometry(15,.045,8,128),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.75}));fenceTop.rotation.x=Math.PI/2;fenceTop.position.y=2.75;geofence.add(fenceTop);
    const target=new T.Group();target.position.y=-.72;scene.add(target);const targetRing=new T.Mesh(new T.RingGeometry(.55,.68,48),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.9,side:T.DoubleSide}));targetRing.rotation.x=-Math.PI/2;target.add(targetRing);
    const route=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xf25a22,transparent:true,opacity:.82}));scene.add(route);
    const vessel=new T.Group();vessel.position.y=.15;scene.add(vessel);let glbVessel=null;
    const loader=new GLTFLoader();loader.load('blender/navrakshak_vessel.glb',g=>{glbVessel=g.scene;glbVessel.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=true;if(o.material)o.material.needsUpdate=true}});const box=new T.Box3().setFromObject(glbVessel),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),maxDim=Math.max(size.x,size.y,size.z)||1,scale=8.5/maxDim;glbVessel.scale.setScalar(scale);glbVessel.position.set(-center.x*scale,-center.y*scale,-center.z*scale);glbVessel.rotation.y=Math.PI;vessel.add(glbVessel);vessel.userData.ready=true;empty.classList.add('hidden')},undefined,e=>{console.warn('Blender GLB unavailable; using fallback.',e);empty.querySelector('span').textContent='Blender vessel unavailable — procedural fallback active';makeFallback()});
    function makeFallback(){const hm=new T.MeshStandardMaterial({color:0xdbe8ee,roughness:.25,metalness:.5}),nm=new T.MeshStandardMaterial({color:0x07325a,roughness:.2,metalness:.55}),am=new T.MeshStandardMaterial({color:0xf25a22,roughness:.2,metalness:.35}),add=(g,m,x,y,z)=>{const q=new T.Mesh(g,m);q.position.set(x,y,z);vessel.add(q);return q};add(new T.BoxGeometry(7,.8,2.2),hm,0,0,0);add(new T.BoxGeometry(5.2,1.8,1.8),nm,-.5,1,0);add(new T.BoxGeometry(5.5,.18,2),am,-.2,1.95,0);add(new T.CylinderGeometry(.07,.09,4.2,14),hm,-.7,4,0);add(new T.CylinderGeometry(.025,.025,1.7,10),am,-.7,6.1,0);add(new T.SphereGeometry(.16,18,18),new T.MeshBasicMaterial({color:0xf25a22}),-.7,7,0);vessel.userData.ready=true}
    const beacon=new T.Mesh(new T.CylinderGeometry(.02,3.2,18,48,1,true),new T.MeshBasicMaterial({color:0xf25a22,transparent:true,opacity:.045,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false}));beacon.position.y=8;scene.add(beacon);
    const hud=document.createElement('div');hud.className='three-hud';hud.innerHTML='<div class="three-chip"><span>3D COMMAND VIEW</span><b id="three-state">AWAITING TELEMETRY</b></div><div class="three-readout"><span>LAT <b id="three-lat">--</b></span><span>LON <b id="three-lon">--</b></span><span>SPD <b id="three-speed">--</b></span><span>HDG <b id="three-heading">--</b></span></div><div class="three-bottom"><span>RADAR / LIVE NODE</span><span id="three-camera-mode">ORBIT CAM</span></div><div class="three-crosshair">+</div>';mount.appendChild(hud);
    const empty=document.createElement('div');empty.className='three-empty';empty.innerHTML='<strong>3D TELEMETRY LAYER</strong><span>Loading Blender vessel…</span>';mount.appendChild(empty);
    let origin=null,dx=0,dz=0,alert=false,yaw=.55,pitch=.32,dist=29,auto=true,mode=0,last=performance.now();const modes=['ORBIT CAM','FOLLOW CAM','CINEMATIC CAM'],trail=[];
    const setTelemetry=d=>{if(!d)return;const lat=Number(d.latitude),lon=Number(d.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;if(!origin)origin={lat,lon};dx=T.MathUtils.clamp((lon-origin.lon)*Math.cos(origin.lat*Math.PI/180)*90000,-45,45);dz=T.MathUtils.clamp(-(lat-origin.lat)*90000,-45,45);const st=String(d.status||'').toUpperCase();alert=d.isAlertActive===true||st.includes('SOS')||st.includes('ALERT');document.getElementById('three-lat').textContent=lat.toFixed(6);document.getElementById('three-lon').textContent=lon.toFixed(6);document.getElementById('three-speed').textContent=Number.isFinite(Number(d.speed))?Number(d.speed).toFixed(1):'--';document.getElementById('three-heading').textContent=Number.isFinite(Number(d.heading))?Number(d.heading).toFixed(0)+'°':'--';document.getElementById('three-state').textContent=alert?'SOS / ALERT':'TELEMETRY LIVE';document.querySelector('.three-chip').classList.toggle('danger',alert);empty.classList.add('hidden');trail.push(new T.Vector3(dx,-.7,dz));if(trail.length>180)trail.shift();const a=new Float32Array(trail.length*3);trail.forEach((p,i)=>{a[i*3]=p.x;a[i*3+1]=p.y;a[i*3+2]=p.z});route.geometry.dispose();route.geometry=new T.BufferGeometry();route.geometry.setAttribute('position',new T.BufferAttribute(a,3))};
    if(window.connectTelemetry)window.connectTelemetry(setTelemetry);
    const resize=()=>{const w=mount.clientWidth||900,h=mount.clientHeight||600;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)};addEventListener('resize',resize);resize();
    mount.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!auto)return;const q=mount.getBoundingClientRect();yaw=((e.clientX-q.left)/q.width-.5)*.8;pitch=.28+((e.clientY-q.top)/q.height-.5)*.3});mount.addEventListener('pointerdown',()=>auto=false);mount.addEventListener('dblclick',()=>{mode=(mode+1)%3;auto=true});mount.addEventListener('wheel',e=>{e.preventDefault();dist=T.MathUtils.clamp(dist+e.deltaY*.018,14,46)},{passive:false});
    document.querySelectorAll('[data-three-mode]').forEach(b=>b.addEventListener('click',()=>{mode=Number(b.dataset.threeMode)||0;auto=true}));addEventListener('nav-three-mode',e=>{mode=Number(e.detail)||0;auto=true});
    const clock=new T.Clock(),animate=now=>{const dt=Math.min(clock.getDelta(),.05),t=now*.001,p=oceanPos.array;for(let i=0;i<p.length;i+=3){const x=oceanBase[i],z=oceanBase[i+1];p[i+2]=oceanBase[i+2]+Math.sin(x*.11+t*1.25)*.18+Math.cos(z*.14+t*.92)*.13+Math.sin((x+z)*.045+t*.55)*.08}oceanPos.needsUpdate=true;oceanGeo.computeVertexNormals();sweep.rotation.z=t*.95;rings.rotation.y=t*.11;horizon.rotation.z=t*.025;vessel.position.x+=(dx-vessel.position.x)*Math.min(1,dt*2.6);vessel.position.z+=(dz-vessel.position.z)*Math.min(1,dt*2.6);vessel.position.y=.15+Math.sin(t*1.25)*.055;vessel.rotation.z=Math.sin(t*.72)*.018;vessel.rotation.x=Math.cos(t*.9)*.012;target.position.x+=(dx-target.position.x)*Math.min(1,dt*4);target.position.z+=(dz-target.position.z)*Math.min(1,dt*4);targetRing.scale.setScalar(1+Math.sin(t*4)*.12);fence.material.opacity=alert?.1:.035;fenceTop.material.opacity=alert?.95:.58;beacon.material.opacity=alert?.14+Math.sin(t*8)*.06:.045;if(!reduced){if(mode===1)yaw+=dt*.08;if(mode===2){yaw=.72+Math.sin(t*.16)*.42;pitch=.38+Math.sin(t*.11)*.08}const cp=new T.Vector3(Math.sin(yaw)*dist,9+pitch*12,Math.cos(yaw)*dist);if(mode===1)cp.add(new T.Vector3(vessel.position.x*.45,1.5,vessel.position.z*.45));camera.position.lerp(cp,.045);camera.lookAt(vessel.position.x*.3,.65,vessel.position.z*.3)}document.getElementById('three-camera-mode').textContent=modes[mode]+(auto?'':' / MANUAL');renderer.render(scene,camera);requestAnimationFrame(animate)};requestAnimationFrame(animate)
  }
  start();
})();