(()=>{
const mount=document.getElementById('three-tracking');
if(!mount||mount.dataset.booted)return;mount.dataset.booted='1';
const threeUrl='https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
const gltfUrl='https://cdn.jsdelivr.net/npm/three@0.179.1/examples/jsm/loaders/GLTFLoader.js';
(async()=>{try{const T=await import(threeUrl);const {GLTFLoader}=await import(gltfUrl);build(T,GLTFLoader)}catch(e){console.error('3D boot failed',e);mount.classList.add('fallback')}})();
function build(T,GLTFLoader){
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const scene=new T.Scene();scene.background=new T.Color(0x071b2b);scene.fog=new T.FogExp2(0x0a2335,.0065);
const camera=new T.PerspectiveCamera(43,1,.1,1200),renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.8));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;mount.appendChild(renderer.domElement);
const hemi=new T.HemisphereLight(0xb9e7ff,0x03101b,1.8);scene.add(hemi);
const key=new T.DirectionalLight(0xffd3a6,4.6);key.position.set(-45,55,-35);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.near=1;key.shadow.camera.far=180;key.shadow.camera.left=-65;key.shadow.camera.right=65;key.shadow.camera.top=65;key.shadow.camera.bottom=-65;scene.add(key);
const fill=new T.PointLight(0x38aef5,24,130,2);fill.position.set(24,12,-24);scene.add(fill);const orange=new T.PointLight(0xf25a22,14,65,2);orange.position.set(-8,5,10);scene.add(orange);
// Cinematic sky dome.
const sky=new T.Mesh(new T.SphereGeometry(520,48,24),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color(0x071321)},mid:{value:new T.Color(0x14617a)},horizon:{value:new T.Color(0xf0a36a)}},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 mid;uniform vec3 horizon;varying vec3 vP;void main(){float h=clamp(normalize(vP).y,-.15,1.0);vec3 c=mix(horizon,mid,smoothstep(-.15,.38,h));c=mix(c,top,smoothstep(.38,1.0,h));gl_FragColor=vec4(c,1.0);}'}));scene.add(sky);
// Warm sun disc + soft halo.
const sunGroup=new T.Group();sunGroup.position.set(-105,48,-125);scene.add(sunGroup);const sunDisc=new T.Mesh(new T.SphereGeometry(7.5,32,20),new T.MeshBasicMaterial({color:0xffb15c}));sunGroup.add(sunDisc);const halo=new T.Mesh(new T.SphereGeometry(13,32,20),new T.MeshBasicMaterial({color:0xff7d45,transparent:true,opacity:.09,blending:T.AdditiveBlending,depthWrite:false}));sunGroup.add(halo);
// Deep, reflective ocean with layered wave motion.
const oceanGeo=new T.PlaneGeometry(280,280,128,128);const ocean=new T.Mesh(oceanGeo,new T.MeshPhysicalMaterial({color:0x06314a,roughness:.13,metalness:.22,clearcoat:.45,clearcoatRoughness:.12,specularIntensity:1,transparent:false}));ocean.rotation.x=-Math.PI/2;ocean.position.y=-1.15;ocean.receiveShadow=true;scene.add(ocean);
const op=oceanGeo.attributes.position,base=new Float32Array(op.array);
const waveAt=(x,z,t)=>Math.sin(x*.12+t*1.05)*.26+Math.cos(z*.16+t*.82)*.18+Math.sin((x+z)*.045+t*.55)*.12+Math.cos((x-z)*.085-t*.72)*.08;
const foamGeo=new T.PlaneGeometry(280,280,64,64),foam=new T.Mesh(foamGeo,new T.MeshBasicMaterial({color:0x79cfe0,transparent:true,opacity:.055,depthWrite:false,blending:T.AdditiveBlending}));foam.rotation.x=-Math.PI/2;foam.position.y=-1.105;scene.add(foam);const fp=foamGeo.attributes.position,fbase=new Float32Array(fp.array);
const grid=new T.GridHelper(220,44,0x4db4d8,0x1b5872);grid.position.y=-.98;grid.material.transparent=true;grid.material.opacity=.12;scene.add(grid);
const particles=new T.BufferGeometry(),pa=new Float32Array((innerWidth<700?900:1700)*3);for(let i=0;i<pa.length;i+=3){pa[i]=(Math.random()-.5)*230;pa[i+1]=Math.random()*38+.5;pa[i+2]=(Math.random()-.5)*230}particles.setAttribute('position',new T.BufferAttribute(pa,3));scene.add(new T.Points(particles,new T.PointsMaterial({color:0xb5ecff,size:.10,transparent:true,opacity:.34,depthWrite:false})));
// Small surface glints for a more photographic water read.
const glintGeo=new T.BufferGeometry(),ga=new Float32Array(500*3);for(let i=0;i<ga.length;i+=3){ga[i]=(Math.random()-.5)*190;ga[i+1]=-1.02;ga[i+2]=(Math.random()-.5)*190}glintGeo.setAttribute('position',new T.BufferAttribute(ga,3));scene.add(new T.Points(glintGeo,new T.PointsMaterial({color:0xd8f8ff,size:.12,transparent:true,opacity:.32,depthWrite:false})));
const rings=new T.Group();rings.position.y=-.92;scene.add(rings);[7,13,20,28].forEach((r,i)=>{const q=new T.Mesh(new T.RingGeometry(r-.045,r+.045,128),new T.MeshBasicMaterial({color:i===3?0x66d9ff:0xf25a22,transparent:true,opacity:i===3?.26:.16,side:T.DoubleSide}));q.rotation.x=-Math.PI/2;rings.add(q)});
const sweep=new T.Mesh(new T.CircleGeometry(28,64,-.12,Math.PI/5),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.075,side:T.DoubleSide,blending:T.AdditiveBlending}));sweep.rotation.x=-Math.PI/2;sweep.position.y=.08;rings.add(sweep);
const fenceG=new T.Group();fenceG.position.y=.4;scene.add(fenceG);const fence=new T.Mesh(new T.CylinderGeometry(15,15,5.5,96,1,true),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.035,wireframe:true}));fenceG.add(fence);const fenceTop=new T.Mesh(new T.TorusGeometry(15,.045,8,128),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.7}));fenceTop.rotation.x=Math.PI/2;fenceTop.position.y=2.75;fenceG.add(fenceTop);
const target=new T.Group();target.position.y=-.72;scene.add(target);const targetRing=new T.Mesh(new T.RingGeometry(.55,.68,48),new T.MeshBasicMaterial({color:0x66d9ff,transparent:true,opacity:.9,side:T.DoubleSide}));targetRing.rotation.x=-Math.PI/2;target.add(targetRing);
const route=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xf25a22,transparent:true,opacity:.82}));scene.add(route);
const vessel=new T.Group();vessel.position.y=.15;scene.add(vessel);let glbVessel=null;
const empty=document.createElement('div');empty.className='three-empty';empty.innerHTML='<strong>3D TELEMETRY LAYER</strong><span>Loading Blender vessel…</span>';mount.appendChild(empty);
const loader=new GLTFLoader();loader.load('blender/navrakshak_vessel.glb',g=>{const vesselNode=g.scene.getObjectByName('NAVRAKHSHAK_VESSEL');if(!vesselNode){console.warn('NAVRAKHSHAK_VESSEL node not found; using procedural fallback');empty.querySelector('span').textContent='Vessel node missing — procedural fallback active';makeFallback();return}if(vesselNode.parent)vesselNode.parent.remove(vesselNode);glbVessel=vesselNode;glbVessel.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material.envMapIntensity=1.15}}});const box=new T.Box3().setFromObject(glbVessel),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),maxSize=Math.max(size.x,size.y,size.z)||1,scale=8.5/maxSize;glbVessel.scale.setScalar(scale);glbVessel.position.set(-center.x*scale,-center.y*scale,-center.z*scale);glbVessel.rotation.y=Math.PI;vessel.add(glbVessel);empty.classList.add('hidden')},undefined,()=>{empty.querySelector('span').textContent='Blender vessel unavailable — procedural fallback active';makeFallback()});
function makeFallback(){const hm=new T.MeshStandardMaterial({color:0xdbe8ee,roughness:.22,metalness:.5}),nm=new T.MeshStandardMaterial({color:0x07325a,roughness:.18,metalness:.55}),am=new T.MeshStandardMaterial({color:0xf25a22,roughness:.2,metalness:.35});const add=(g,m,x,y,z)=>{const q=new T.Mesh(g,m);q.position.set(x,y,z);q.castShadow=true;q.receiveShadow=true;vessel.add(q)};add(new T.CapsuleGeometry(1.05,5.8,6,18),hm,0,0,0);add(new T.BoxGeometry(5.2,1.8,1.8),nm,-.5,1,0);add(new T.BoxGeometry(5.5,.18,2),am,-.2,1.95,0);add(new T.CylinderGeometry(.07,.09,4.2,14),hm,-.7,4,0);add(new T.CylinderGeometry(.025,.025,1.7,10),am,-.7,6.1,0);add(new T.SphereGeometry(.16,18,18),new T.MeshBasicMaterial({color:0xf25a22}),-.7,7,0);vessel.userData.ready=true;empty.classList.add('hidden')}
const beacon=new T.Mesh(new T.CylinderGeometry(.02,3.2,18,48,1,true),new T.MeshBasicMaterial({color:0xf25a22,transparent:true,opacity:.045,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false}));beacon.position.y=8;scene.add(beacon);
const hud=document.createElement('div');hud.className='three-hud';hud.innerHTML='<div class="three-chip"><span>3D COMMAND VIEW</span><b id="three-state">AWAITING TELEMETRY</b></div><div class="three-readout"><span>LAT <b id="three-lat">--</b></span><span>LON <b id="three-lon">--</b></span><span>SPD <b id="three-speed">--</b></span><span>HDG <b id="three-heading">--</b></span></div><div class="three-bottom"><span>RADAR / LIVE NODE</span><span id="three-camera-mode">ORBIT CAM</span></div><div class="three-crosshair">+</div>';mount.appendChild(hud);
let origin=null,dx=0,dz=0,alert=false,mode=0,dist=29,yaw=.55,pitch=.32,dragging=false,lastX=0,lastY=0,auto=true;const trail=[];const modes=['ORBIT CAM','FOLLOW CAM','CINEMATIC CAM'];
function setTelemetry(d){if(!d)return;const lat=Number(d.latitude),lon=Number(d.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;if(!origin)origin={lat,lon};dx=T.MathUtils.clamp((lon-origin.lon)*Math.cos(origin.lat*Math.PI/180)*90000,-45,45);dz=T.MathUtils.clamp(-(lat-origin.lat)*90000,-45,45);const st=String(d.status||'').toUpperCase();alert=d.isAlertActive===true||st.includes('SOS')||st.includes('ALERT');document.getElementById('three-lat').textContent=lat.toFixed(6);document.getElementById('three-lon').textContent=lon.toFixed(6);document.getElementById('three-speed').textContent=Number.isFinite(Number(d.speed))?Number(d.speed).toFixed(1):'--';document.getElementById('three-heading').textContent=Number.isFinite(Number(d.heading))?Number(d.heading).toFixed(0)+'°':'--';document.getElementById('three-state').textContent=alert?'SOS / ALERT':'TELEMETRY LIVE';document.querySelector('.three-chip').classList.toggle('danger',alert);empty.classList.add('hidden');trail.push(new T.Vector3(dx,-.7,dz));if(trail.length>180)trail.shift();const a=new Float32Array(trail.length*3);trail.forEach((p,i)=>{a[i*3]=p.x;a[i*3+1]=p.y;a[i*3+2]=p.z});route.geometry.dispose();route.geometry=new T.BufferGeometry();route.geometry.setAttribute('position',new T.BufferAttribute(a,3))}
if(window.connectTelemetry)window.connectTelemetry(setTelemetry);
function setMode(n){mode=((Number(n)||0)%3+3)%3;auto=true;document.getElementById('three-camera-mode').textContent=modes[mode]}
mount.querySelectorAll('[data-three-mode]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();setMode(b.dataset.threeMode)}));addEventListener('nav-three-mode',e=>setMode(e.detail));
mount.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;dragging=true;auto=false;lastX=e.clientX;lastY=e.clientY;mount.setPointerCapture?.(e.pointerId);mount.classList.add('dragging');e.preventDefault()});
mount.addEventListener('pointermove',e=>{if(!dragging)return;const dxm=e.clientX-lastX,dym=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw-=dxm*.008;pitch=T.MathUtils.clamp(pitch+dym*.006,-.15,.85);e.preventDefault()});
const endDrag=e=>{if(!dragging)return;dragging=false;mount.releasePointerCapture?.(e.pointerId);mount.classList.remove('dragging')};mount.addEventListener('pointerup',endDrag);mount.addEventListener('pointercancel',endDrag);mount.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse'&&dragging)endDrag(e)});
mount.addEventListener('wheel',e=>{e.preventDefault();dist=T.MathUtils.clamp(dist+e.deltaY*.018,12,55);auto=false},{passive:false});mount.addEventListener('dblclick',e=>{if(e.target.closest('button'))return;setMode(mode+1)});
const resize=()=>{const w=mount.clientWidth||900,h=mount.clientHeight||600;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)};addEventListener('resize',resize);resize();
const clock=new T.Clock();function animate(now){const dt=Math.min(clock.getDelta(),.05),t=now*.001,p=op.array,fpv=fp.array;for(let i=0;i<p.length;i+=3){const x=base[i],z=base[i+1];p[i+2]=base[i+2]+waveAt(x,z,t)}for(let i=0;i<fpv.length;i+=3){const x=fbase[i],z=fbase[i+1];fpv[i+2]=fbase[i+2]+waveAt(x,z,t)*.72}op.needsUpdate=true;fp.needsUpdate=true;oceanGeo.computeVertexNormals();sweep.rotation.z=t*.95;rings.rotation.y=t*.11;sunGroup.rotation.y=t*.015;
const seaY=waveAt(dx,dz,t);vessel.position.x+=(dx-vessel.position.x)*Math.min(1,dt*2.6);vessel.position.z+=(dz-vessel.position.z)*Math.min(1,dt*2.6);vessel.position.y=.15+seaY*.34+Math.sin(t*1.25)*.045;const slopeX=(waveAt(dx+.6,dz,t)-waveAt(dx-.6,dz,t))*.22;const slopeZ=(waveAt(dx,dz+.6,t)-waveAt(dx,dz-.6,t))*.22;vessel.rotation.x+=(-slopeZ-vessel.rotation.x)*Math.min(1,dt*2.2);vessel.rotation.z+=(slopeX-vessel.rotation.z)*Math.min(1,dt*2.2);
target.position.x+=(dx-target.position.x)*Math.min(1,dt*4);target.position.z+=(dz-target.position.z)*Math.min(1,dt*4);targetRing.scale.setScalar(1+Math.sin(t*4)*.12);fence.material.opacity=alert?.1:.035;fenceTop.material.opacity=alert?.95:.7;beacon.material.opacity=alert?.14+Math.sin(t*8)*.06:.045;
if(!reduced&&!dragging){if(mode===1){yaw+=dt*.08}else if(mode===2){yaw=.72+Math.sin(t*.16)*.42;pitch=.38+Math.sin(t*.11)*.08}}const cp=new T.Vector3(Math.sin(yaw)*dist,9+pitch*12,Math.cos(yaw)*dist);if(mode===1)cp.add(new T.Vector3(vessel.position.x*.45,1.5,vessel.position.z*.45));camera.position.lerp(cp,dragging?.16:.045);camera.lookAt(vessel.position.x*.3,.65+seaY*.18,vessel.position.z*.3);document.getElementById('three-camera-mode').textContent=modes[mode]+(dragging||!auto?' / MANUAL':'');renderer.render(scene,camera);requestAnimationFrame(animate)}requestAnimationFrame(animate)
}
})();